### ISSUE TITLE
{$wpdb->prefix}cities table is not created automatically, label & instruction improvement

### ISSUE THREAD

**Issue by miaosun** [Beee4life/acf-city-selector#62]
> Impact
The plugin adds a database table named {$wpdb->prefix}cities upon plugin activation and imports cities from 3 different countries.

1. Plugin activation doesn't create any database table, had to run the following sql code to create the table manually
`CREATE TABLE <?php echo wp_cities (
                    id int(6) unsigned NOT NULL auto_increment,
                    city_name varchar(50) NULL,
                    state_code varchar(3) NULL,
                    state_name varchar(50) NULL,
                    country_code varchar(2) NULL,
                    country varchar(50) NULL,
                    PRIMARY KEY  (id)
                    )
                    COLLATE utf8mb4_unicode_ci;`

The option of importing cities from the existing 3 countries is in plugin's "Settings" page.

2. When a default country is set in custom fields settings, the default value (label) for 'State' option should be 'Select a province/state", instead of 'Select a country first'

- with default country set
![incorrect label](https://imgur.com/Q6sRoQr.jpg)

- no default country set
![correct label](https://imgur.com/EGH05Ey.jpg)

3. request of feature:

Currently in "Fields to use", there're following 4 options
![correct label](https://imgur.com/EjWRDEI.jpg)
Can you also add the option "State/province + City", for the case to use only 1 country?

Thanks a lot for the awesome plugin, regards!

**Comment by Beee4life** [comment]
1. As you can see on [this line](https://github.com/Beee4life/acf-city-selector/blob/master/ACF_City_Selector.php#L67) the function `acfcs_plugin_activation` is called on plugin_activation.

There is only 1 instance I can think of where this hook is not called and that is when it's used as a MU plugin. That won't work yet.

If that is not the case, then I suspect it might have to do with an option which is set too early, which is checked. Since it's set too early, [this IF](https://github.com/Beee4life/acf-city-selector/blob/master/ACF_City_Selector.php#L153) is not 'hit'.

You can test it by deleting `acfcs_db_version` from wp_options.
Delete the table wp_cities. 
Deactivate the plugin, then reactivate it.

2. true just didn't get around to it.

3. I can and I might, but don't hold your breath for it...

**Comment by Beee4life** [comment]
@miaosun 

1) You were right, I missed something. Someone emailed me some errors, which explained the issue further. I have fixed this in the [last release](https://github.com/Beee4life/acf-city-selector/releases/tag/0.27.1).
2) Also fixed in last release.
3) Your request is available right now in a [beta release](https://github.com/Beee4life/acf-city-selector/releases/tag/0.28.0-beta1). Feel free to test it and give me feedback.

**Comment by Beee4life** [comment]
Closing this since it's fixed.
